[package]
name = "ecstasy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
edict = { git = "https://github.com/akhilman/edict.git" }
smallvec = "1.7.0"
